#Pre16Name 

Pre16shortname <- c(
              "Timestamp",
              "Navterm",
              "PythonScript",
              "AmazonE2",
              "InstallMothur",
              "RunQIIME",
              "ExecRScript",
              "ChooseEcoStat",
              "InstallAmazonE2",
              "AssembleMeta",
              "UseGithub",
              "RunBLAST",
              "UseMGRAST",
              "UseAPI",
              "UnderstandCD",
              "UnderstandPY",
              "IlluminaData",
              "SumSequence",
              "RunR",
              "QIIMEvsMothur",
              "BIOMFiles_NoPost",
              "TwoMicrobial",
              "CDpkg",
              "StructureOTU",
              "KnowKMER",
              "KnowContig",
              "KnowEC2",
              "KnowWithinsample",
              "KnowMetadata",
              "KnowShotgun",
              "KnowMetagenomeBin",
              "KnowHPCC",
              "KnowMetavsAssem",
              "ExecuteShotgun",
              "ExecuteAmplicon",
              "InformedAmpliconQiime",
              "InformedAmpliconMothur",
              "DiffAssembledMetagenomic",
              "LimitationsMetagenomic",
              "AdvantageDisadvMetagemonic",
              "UnderstandKmer",
              "QualShotgun",
              "RpgkAnalyzeData",
              "MoveDataIntoR",
              "MoveFilesTerminal",
              "EvalRawSequence",
              "SearchPublicDatasets",
              "CannotShotgunWOHelp",
              "CannotAmpliconWOHelp",
              "CanCompleteLotofTime",
              "CanCompleteMentor",
              "CanOvercomeifStuck",
              "CannotWOHelp",
              "MinimizeLimitationsSequencing",
              "UnderstandTechLimitations",
              "UnderstandMGRAST",
              "UseGit",
              "NavUnix",
              "MakeE2Key",
              "InstallAuxSoftware",
              "UseFastQC",
              "SumInfoSequenceFiles",
              "CalcOTU",
              "TrimSeqErrors",
              "AssembleMetagenome",
              "BinMetagenome",
              "DiffDataModels",
              "TestHypotheses",
              "IDPublicSequenceData",
              "ObtainSeqfromMGRAST",
              "SupposeStory1",
              "SupposeStory2",
              "Age",
              "AcadStatus",
              "Gender",
              "Ethnicity",
              "ExpectationsPre",
              "AnonCodePre"
)










